# Microservices Architecture Docker Compose
# FacebookConnect (External) + ChatBotCore (Internal) Services
version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: chatbot-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: chatbot_mvp
      POSTGRES_USER: chatbot_user
      POSTGRES_PASSWORD: chatbot_pass123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "55433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/internal/ChatBotCore/migrations:/docker-entrypoint-initdb.d
    networks:
      - chatbot-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot_user -d chatbot_mvp"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ChatBotCore Service (Internal - Business Logic)
  chatbot-core:
    build:
      context: ./backend/internal/ChatBotCore
      dockerfile: Dockerfile
    container_name: chatbot-core
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      # Database Configuration
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: chatbot_mvp
      DB_USER: chatbot_user
      DB_PASSWORD: chatbot_pass123
      DB_SSL_MODE: disable
      DB_MAX_OPEN_CONNS: 25
      DB_MAX_IDLE_CONNS: 5
      DB_CONN_MAX_LIFETIME: 300s
      
      # Server Configuration
      PORT: 8086
      GIN_MODE: release
      
      # Performance Configuration
      WORKER_POOL_SIZE: 10
      MESSAGE_QUEUE_SIZE: 1000
      
      # Logging
      LOG_LEVEL: info
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - chatbot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8086/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # FacebookConnect Service (External - Integration Layer)
  facebook-connect:
    build:
      context: ./backend/external/FacebookConnect
      dockerfile: Dockerfile
    container_name: facebook-connect
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      # Server Configuration
      PORT: 8085
      GIN_MODE: release
      
      # Facebook Configuration
      FB_VERIFY_TOKEN: ${FB_VERIFY_TOKEN:-your_facebook_verify_token}
      FB_PAGE_TOKEN: ${FB_PAGE_TOKEN:-your_facebook_page_token}
      
      # ChatBotCore Service Configuration
      CHATBOT_CORE_URL: http://chatbot-core:8086
      
      # Logging
      LOG_LEVEL: info
    depends_on:
      chatbot-core:
        condition: service_healthy
    networks:
      - chatbot-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8085/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Frontend (Optional - for management UI)
  frontend:
    build:
      context: ./frontend-next
      dockerfile: Dockerfile
    container_name: chatbot-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://chatbot-core:8086
    depends_on:
      - chatbot-core
      - facebook-connect
    networks:
      - chatbot-network

volumes:
  postgres_data:
    driver: local

networks:
  chatbot-network:
    driver: bridge
