version: '3.8'

services:
  # ChatBotCore Service
  chatbot-core:
    build:
      context: .
      dockerfile: backend/internal/ChatBotCore/Dockerfile
    ports:
      - "8090:8090"
    environment:
      - GIN_MODE=release
      - LOG_LEVEL=info
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8090/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - ruay-network

  # FacebookConnect Service  
  facebook-connect:
    build:
      context: .
      dockerfile: backend/external/FacebookConnect/Dockerfile
    ports:
      - "8091:8091"
    environment:
      - GIN_MODE=release
      - LOG_LEVEL=info
    depends_on:
      - chatbot-core
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8091/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    networks:
      - ruay-network

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://chatbot-core:8090
      - NEXT_PUBLIC_FACEBOOK_API_URL=http://facebook-connect:8091
    depends_on:
      - chatbot-core
      - facebook-connect
    restart: unless-stopped
    networks:
      - ruay-network

networks:
  ruay-network:
    driver: bridge
