services:
  backend:
    build: .
    ports:
      - "3006:3006"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: ruayAutoMsg
      POSTGRES_USER: ruay
      POSTGRES_PASSWORD: ruay1234
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./keyword_responses.sql:/docker-entrypoint-initdb.d/keyword_responses.sql:ro
  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173"
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
 
volumes:
  pgdata:
