CREATE TABLE IF NOT EXISTS keyword_responses (
   id SERIAL PRIMARY KEY,
  keyword TEXT NOT NULL,
  response TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
