# Add this to your docker-compose.yml file

  frontend-next:
    build: 
      context: ./frontend-next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://backend:3006
    depends_on:
      - backend
    restart: unless-stopped
